WELCOME = "WELCOME"
AWAITING_LANGUAGE_CHOICE = "AWAITING_LANGUAGE_CHOICE"
AWAITING_ENTRY_CHOICE = "AWAITING_ENTRY_CHOICE"

CREATE_PROFILE_NAME = "CREATE_PROFILE_NAME"
CREATE_PROFILE_PHONE = "CREATE_PROFILE_PHONE"
CREATE_PROFILE_PASSWORD = "CREATE_PROFILE_PASSWORD"
CREATE_PROFILE_CONFIRM = "CREATE_PROFILE_CONFIRM"

LOGIN_IDENTIFIER = "LOGIN_IDENTIFIER"
LOGIN_PASSWORD = "LOGIN_PASSWORD"
AUTHENTICATED_HOME = "AUTHENTICATED_HOME"

SEND_MONEY_RECIPIENT = "SEND_MONEY_RECIPIENT"
SEND_MONEY_AMOUNT = "SEND_MONEY_AMOUNT"
SEND_MONEY_CONFIRM = "SEND_MONEY_CONFIRM"

PAY_BILL_TYPE = "PAY_BILL_TYPE"
PAY_BILL_AMOUNT = "PAY_BILL_AMOUNT"
PAY_BILL_CONFIRM = "PAY_BILL_CONFIRM"

BUY_AIRTIME_AMOUNT = "BUY_AIRTIME_AMOUNT"
BUY_AIRTIME_CONFIRM = "BUY_AIRTIME_CONFIRM"

CHECK_BALANCE = "CHECK_BALANCE"
AWAITING_GENERAL_COMMAND = "AWAITING_GENERAL_COMMAND"

SUPPORTED_LANGS = ["en", "sn", "nd"]
