def speak(lang: str, key: str, **kwargs) -> str:
    prompts = {
        "en": {
            "welcome": "Welcome to Jonten. Please choose your language. Say English. Mauya ku Jonten. Sarudzai mutauro wenyu. Itai Shona. Siyakwamukela ku Jonten. Khetha ulimi lwakho. Tsho Ndebele.",
            "entry_choice": "Say create profile to register, or say login to access your account.",
            "ask_name": "Please say your full name.",
            "ask_phone": "Please say your phone number.",
            "ask_language": "Please choose your language. Say English, Shona, or Ndebele.",
            "ask_password": "Please say your four digit password.",
            "confirm_profile": "Please confirm your details. Name: {name}. Phone: {phone}. Language: {language}. Say confirm to continue or cancel to restart.",
            "profile_created": "Your profile has been created successfully. You are now logged in.",
            "ask_login_id": "Please say your phone number to log in.",
            "login_success": "Login successful. What would you like to do? You can say check balance, send money, buy airtime, or pay bill.",
            "ask_login_password": "Please say your password.",
            "invalid_login": "I could not verify your details. Please try again.",
            "balance": "Your account balance is {balance} dollars.",
            "ask_recipient": "Who do you want to send money to?",
            "ask_amount": "How much would you like to send?",
            "confirm_send": "You are sending {amount} dollars to {recipient}. Say confirm to continue or cancel to stop.",
            "send_success": "Transaction successful. {amount} dollars has been sent to {recipient}.",
            "ask_bill_type": "Which bill would you like to pay? You can say electricity or school fees.",
            "ask_bill_amount": "How much would you like to pay?",
            "confirm_bill": "You are paying {amount} dollars for {biller}. Say confirm to continue or cancel to stop.",
            "bill_success": "Payment successful. {amount} dollars has been paid for {biller}.",
            "ask_airtime_amount": "How much airtime would you like to buy?",
            "confirm_airtime": "You are buying {amount} dollars airtime. Say confirm to continue or cancel to stop.",
            "airtime_success": "Airtime purchase successful. {amount} dollars airtime has been purchased.",
            "cancelled": "Action cancelled. What would you like to do next?",
            "logout_success": "You have been logged out successfully.",
            "fallback": "I did not understand that. Please try again.",
        },
        "sn": {
            "welcome": "Welcome to Jonten. Please choose your language. Say English. Mauya ku Jonten. Sarudzai mutauro wenyu. Itai Shona. Siyakwamukela ku Jonten. Khetha ulimi lwakho. Tsho Ndebele.",
            "entry_choice": "Itai gadzira account kuti munyorere, kana kuti login kuti mupinde muaccount yenyu.",
            "ask_name": "Ndapota taurai zita renyu rose.",
            "ask_phone": "Ndapota taurai nhamba dzenhare dzenyu.",
            "ask_language": "Sarudzai mutauro wenyu. Itai English, Shona, kana Ndebele.",
            "ask_password": "Ndapota taurai password yenyu ine manhamba mana.",
            "confirm_profile": "Ndapota simbisa mashoko enyu. Zita: {name}. Nhamba: {phone}. Mutauro: {language}. Itai confirm kuti muenderere mberi kana cancel kuti mutange patsva.",
            "profile_created": "Profile yenyu yagadzirwa zvakanaka. Mapinda muaccount.",
            "ask_login_id": "Ndapota taurai nhamba dzenhare kuti mupinde.",
            "login_success": "Mapinda zvakanaka. Mungadei kuita? Munogona kuti check balance, send money, buy airtime, kana pay bill.",
            "ask_login_password": "Ndapota taurai password yenyu.",
            "invalid_login": "Handina kukwanisa kuona mashoko enyu. Ndapota edzai zvakare.",
            "balance": "Mari iri muaccount yenyu i {balance} dollars.",
            "ask_recipient": "Munoda kutumira mari kuna ani?",
            "ask_amount": "Mari yamunoda kutumira imarii?",
            "confirm_send": "Muri kutumira {amount} dollars kuna {recipient}. Itai confirm kuti muenderere mberi kana cancel kuti mire.",
            "send_success": "Kutumira kwabudirira. {amount} dollars yatumirwa kuna {recipient}.",
            "ask_bill_type": "Nderipi bhiri ramunoda kubhadhara? Itai electricity kana school fees.",
            "ask_bill_amount": "Mari yamunoda kubhadhara imarii?",
            "confirm_bill": "Muri kubhadhara {amount} dollars ye {biller}. Itai confirm kuti muenderere mberi kana cancel kuti mire.",
            "bill_success": "Kubhadhara kwabudirira. {amount} dollars yabhadharwa ye {biller}.",
            "ask_airtime_amount": "Munoda kutenga airtime yemarii?",
            "confirm_airtime": "Muri kutenga airtime ye {amount} dollars. Itai confirm kuti muenderere mberi kana cancel kuti mire.",
            "airtime_success": "Kutenga airtime kwabudirira. Airtime ye {amount} dollars yatengwa.",
            "cancelled": "Zvamiswa. Mungadei kuita zvino?",
            "logout_success": "Mabuda muaccount zvakanaka.",
            "fallback": "Handina kunyatsonzwa izvozvo. Ndapota taurai zvakare.",
        },
        "nd": {
            "welcome": "Welcome to Jonten. Please choose your language. Say English. Mauya ku Jonten. Sarudzai mutauro wenyu. Itai Shona. Siyakwamukela ku Jonten. Khetha ulimi lwakho. Tsho Ndebele.",
            "entry_choice": "Tsho create profile ukubhalisa, loba login ukungena ku account yakho.",
            "ask_name": "Ngicela utsho ibizo lakho eligcweleyo.",
            "ask_phone": "Ngicela utsho inombolo yakho yocingo.",
            "ask_language": "Khetha ulimi lwakho. Tsho English, Shona, loba Ndebele.",
            "ask_password": "Ngicela utsho ipassword yakho enamadijithi amane.",
            "confirm_profile": "Ngicela uqinisekise imininingwane yakho. Ibizo: {name}. Inombolo: {phone}. Ulimi: {language}. Tsho confirm ukuqhubeka kumbe cancel ukuqala kutsha.",
            "profile_created": "Iphrofayili yakho yenziwe ngempumelelo. Usungene ku account yakho.",
            "ask_login_id": "Ngicela utsho inombolo yakho yocingo ukuze ungene.",
            "login_success": "Ungene ngempumelelo. Ufuna ukwenzani? Ungatsho check balance, send money, buy airtime, loba pay bill.",
            "ask_login_password": "Ngicela utsho ipassword yakho.",
            "invalid_login": "Angenelisanga ukuqinisekisa imininingwane yakho. Zama njalo.",
            "balance": "Imali ekwi account yakho i {balance} dollars.",
            "ask_recipient": "Ufuna ukuthumela imali kubani?",
            "ask_amount": "Ufuna ukuthumela malini?",
            "confirm_send": "Uthumela {amount} dollars ku {recipient}. Tsho confirm ukuqhubeka kumbe cancel ukuma.",
            "send_success": "Ukuthumela kuphumelele. {amount} dollars zithunyelwe ku {recipient}.",
            "ask_bill_type": "Ufuna ukubhadalela yiphi ibhili? Tsho electricity kumbe school fees.",
            "ask_bill_amount": "Ufuna ukubhadala malini?",
            "confirm_bill": "Ubhadala {amount} dollars ye {biller}. Tsho confirm ukuqhubeka kumbe cancel ukuma.",
            "bill_success": "Ukubhadala kuphumelele. {amount} dollars zibhadelwe i {biller}.",
            "ask_airtime_amount": "Ufuna ukuthenga airtime engakanani?",
            "confirm_airtime": "Uthenga airtime ye {amount} dollars. Tsho confirm ukuqhubeka kumbe cancel ukuma.",
            "airtime_success": "Ukuthenga airtime kuphumelele. Airtime ye {amount} dollars ithengiwe.",
            "cancelled": "Kukhanseliwe. Ufuna ukwenzani manje?",
            "logout_success": "Usuphume ku account yakho ngempumelelo.",
            "fallback": "Angikuzwanga kahle. Ngicela uphinde njalo.",
        }
    }

    template = prompts.get(lang, prompts["en"]).get(key, prompts["en"]["fallback"])
    return template.format(**kwargs)
